[package]
name = "gsr-ui"
type = "executable"
version = "1.13.9"
platforms = ["posix"]

[lang.cpp]
version = "c++17"

[config]
ignore_dirs = ["build", "tools"]

[define]
_FILE_OFFSET_BITS = "64"

[dependencies]
xcomposite = ">=0"
xfixes = ">=0"
xext = ">=0"
xi = ">=0"
xcursor = ">=1"
xrandr = ">=0.5"
libpulse-simple = ">=0"
libdrm = ">=2"
wayland-client = ">=1"
